DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  gig_id INTEGER REFERENCES gigs(id) ON DELETE CASCADE,
  client_id INTEGER REFERENCES users(id) ON DELETE CASCADE,

  rating INTEGER NOT NULL,
  review TEXT NOT NULL,
  status VARCHAR(255) NOT NULL,
  order_date TIMESTAMP,
  finished_date DATE NOT NULL
);